# Generated by Django 5.1.4 on 2025-01-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_security_user", "0002_alter_user_created_alter_user_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_freeze",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
