# Generated by Django 5.1.4 on 2025-02-08 07:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_security_user", "0003_user_is_freeze"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=cloudinary.models.CloudinaryField(
                default="https://png.pngtree.com/png-clipart/20231015/original/pngtree-man-avatar-clipart-illustration-png-image_13302499.png",
                max_length=255,
                verbose_name="profile_image",
            ),
        ),
    ]
