# Generated by Django 5.1.4 on 2025-02-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_root_api_security_user", "0005_alter_user_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.FileField(blank=True, null=True, upload_to="photos"),
        ),
    ]
